### ISSUE TITLE
Change - Preparation of s-optimization input (ported from gitlab)

### ISSUE THREAD

**Issue by SalomeRonja** [rinikerlab/reeds#16]
by @candidechamp :

The code converting the output of the energy offset analysis seems to produce .imd files which don't have the proper number of s-values for s-optimization step. 

Right now, the code ensures that if you had 11 s-values at the end of the energy offset estimation (uniformly distributed on a log scale), then you should also have 11 s-values for the first step of the s-optimization. 

However, now that we are using the SSM approach, it will enforce that we have N s = 1 replicas (where N is the number of end states). The code therefore redistributes the 11 - N other s-values uniformely, which means that the s-distribution of lower s-values is smaller. (In my specific example with CHK1, N = 5, so we are left with only 6 replicas with s != 1). 

I think it would be better to add the replicas with s = 1 such that we keep all of the other s-values just as they are. We would therefore keep the same s-distribution, and add (N-1) replicas for s = 1.

What do you think @SchroederB  @SalomeRonja  @epecora ? This is what seems intiutive to me (and that's why I file it as a bug), but maybe you think differently? Reducing the number of s-values also in principle means we need to do even more s-optimization. 

I will fix this I you give me the thumbs up that it is the functionality that we want to have! 
(I had planned to change this part of the code anyways, as this s-distribution would have to change if we find out that using a different initial s-distribution could lead to a shorter s-optimization phase).

**Comment by candidechamp** [comment]
The changes are finally implemented back into the main branch with #65
